language: java
jdk:
  - oraclejdk8
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  domain: $OPENSHIFT_DOMAIN
  app: $OPENSHIFT_APP
  on:
    repo: withdude2/dearmypet
    branch: master