language: java
script: mvn package -Popenshift
jdk:
  - oraclejdk8
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  domain: dearmypet.net
  app: dearmypet
  on: master